# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "// todd: behunin"
email: todd@behun.in
description: > # this means to ignore newlines until "baseurl:"
  Just another developer navigating an ever-changing technological landscape.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://behun.in" # the base hostname & protocol for your site
twitter_username: tbehunin
github_username:  tbehunin

# Build settings
markdown: kramdown
